import type { ArticleCommandUseCase } from "@/core/article/application/port/in/ArticleCommandUseCase";
import type { ArticleMediaUploadUseCase } from "@/core/article/application/port/in/ArticleMediaUploadUseCase";
import type { GetArticleDetailUseCase } from "@/core/article/application/port/in/GetArticleDetailUseCase";
import type { GetArticlePageUseCase } from "@/core/article/application/port/in/GetArticlePageUseCase";
import type { ArticleCommandPort } from "@/core/article/application/port/out/ArticleCommandPort";
import type { ArticleDetailQueryPort } from "@/core/article/application/port/out/ArticleDetailQueryPort";
import type { MediaStoragePort } from "@/core/article/application/port/out/MediaStoragePort";
import type { CreateSessionTokenUseCase } from "@/core/auth/application/port/in/CreateSessionTokenUseCase";
import type { GetCookieOptionsUseCase } from "@/core/auth/application/port/in/GetCookieOptionsUseCase";
import type { LoginWithGoogleCodeUseCase } from "@/core/auth/application/port/in/LoginWithGoogleCodeUseCase";
import type { ResolveSessionUseCase } from "@/core/auth/application/port/in/ResolveSessionUseCase";
import type { VerifyAccessTokenUseCase } from "@/core/auth/application/port/in/VerifyAccessTokenUseCase";
import type { VerifyRefreshTokenUseCase } from "@/core/auth/application/port/in/VerifyRefreshTokenUseCase";
import type { AuthCommandPort } from "@/core/auth/application/port/out/AuthCommandPort";
import type { AuthQueryPort } from "@/core/auth/application/port/out/AuthQueryPort";
import type { GoogleOAuthPort } from "@/core/auth/application/port/out/GoogleOAuthPort";
import type { TokenCodecPort } from "@/core/auth/application/port/out/TokenCodecPort";
import type { CookieConfig } from "@/core/auth/config/CookieConfig";
import type { CommentCommandUseCase } from "@/core/comment/application/port/in/CommentCommandUseCase";
import type { ListArticleCommentsUseCase } from "@/core/comment/application/port/in/ListArticleCommentsUseCase";
import type { CommentCommandPort } from "@/core/comment/application/port/out/CommentCommandPort";
import type { CommentQueryPort } from "@/core/comment/application/port/out/CommentQueryPort";
import type { ClockPort } from "@/core/common/application/port/out/ClockPort";
import type { TransactionPort } from "@/core/common/application/port/out/TransactionPort";
import type { GetFeedHomeUseCase } from "@/core/feed/application/port/in/GetFeedHomeUseCase";
import type { ListFeedUseCase } from "@/core/feed/application/port/in/ListFeedUseCase";
import type { FeedQueryPort } from "@/core/feed/application/port/out/FeedQueryPort";
import type { SearchGeocodingUseCase } from "@/core/geocoding/application/port/in/SearchGeocodingUseCase";
import type { GeocodingSearchPort } from "@/core/geocoding/application/port/out/GeocodingSearchPort";
import type { HikingCommandUseCase } from "@/core/hiking/application/port/in/HikingCommandUseCase";
import type { HikingCommandPort } from "@/core/hiking/application/port/out/HikingCommandPort";
import type { LikeCommandUseCase } from "@/core/like/application/port/in/LikeCommandUseCase";
import type { LikeCommandPort } from "@/core/like/application/port/out/LikeCommandPort";
import type { GetMemberManagementUseCase } from "@/core/member/application/port/in/GetMemberManagementUseCase";
import type { ListMembersUseCase } from "@/core/member/application/port/in/ListMembersUseCase";
import type { UpdateMemberRoleUseCase } from "@/core/member/application/port/in/UpdateMemberRoleUseCase";
import type { MemberCommandPort } from "@/core/member/application/port/out/MemberCommandPort";
import type { MemberQueryPort } from "@/core/member/application/port/out/MemberQueryPort";
import type { CreateNotificationsUseCase } from "@/core/notification/application/port/in/CreateNotificationsUseCase";
import type { ListNotificationsUseCase } from "@/core/notification/application/port/in/ListNotificationsUseCase";
import type { MarkAllNotificationsReadUseCase } from "@/core/notification/application/port/in/MarkAllNotificationsReadUseCase";
import type { MarkNotificationReadUseCase } from "@/core/notification/application/port/in/MarkNotificationReadUseCase";
import type { NotificationCommandPort } from "@/core/notification/application/port/out/NotificationCommandPort";
import type { NotificationQueryPort } from "@/core/notification/application/port/out/NotificationQueryPort";
import type { ProfileImageUploadUseCase } from "@/core/profile/application/port/in/ProfileImageUploadUseCase";
import type { UpdateDisplayNameUseCase } from "@/core/profile/application/port/in/UpdateDisplayNameUseCase";
import type { UpdateEmailUseCase } from "@/core/profile/application/port/in/UpdateEmailUseCase";
import type { UpdateProfileImageUseCase } from "@/core/profile/application/port/in/UpdateProfileImageUseCase";
import type { ProfileCommandPort } from "@/core/profile/application/port/out/ProfileCommandPort";
import type { ProfileImageStoragePort } from "@/core/profile/application/port/out/ProfileImageStoragePort";
import type { ProfileQueryPort } from "@/core/profile/application/port/out/ProfileQueryPort";

export type UseCaseBeans = {
	ArticleCommandUseCase: ArticleCommandUseCase;
	ArticleMediaUploadUseCase: ArticleMediaUploadUseCase;
	CommentCommandUseCase: CommentCommandUseCase;
	HikingCommandUseCase: HikingCommandUseCase;
	LikeCommandUseCase: LikeCommandUseCase;
	ListArticleCommentsUseCase: ListArticleCommentsUseCase;
	ListFeedUseCase: ListFeedUseCase;
	LoginWithGoogleCodeUseCase: LoginWithGoogleCodeUseCase;
	ResolveSessionUseCase: ResolveSessionUseCase;
	VerifyAccessTokenUseCase: VerifyAccessTokenUseCase;
	VerifyRefreshTokenUseCase: VerifyRefreshTokenUseCase;
	CreateSessionTokenUseCase: CreateSessionTokenUseCase;
	GetCookieOptionsUseCase: GetCookieOptionsUseCase;
	GetArticleDetailUseCase: GetArticleDetailUseCase;
	GetArticlePageUseCase: GetArticlePageUseCase;
	GetFeedHomeUseCase: GetFeedHomeUseCase;
	GetMemberManagementUseCase: GetMemberManagementUseCase;
	ListMembersUseCase: ListMembersUseCase;
	CreateNotificationsUseCase: CreateNotificationsUseCase;
	ListNotificationsUseCase: ListNotificationsUseCase;
	MarkAllNotificationsReadUseCase: MarkAllNotificationsReadUseCase;
	MarkNotificationReadUseCase: MarkNotificationReadUseCase;
	UpdateMemberRoleUseCase: UpdateMemberRoleUseCase;
	ProfileImageUploadUseCase: ProfileImageUploadUseCase;
	UpdateDisplayNameUseCase: UpdateDisplayNameUseCase;
	UpdateEmailUseCase: UpdateEmailUseCase;
	UpdateProfileImageUseCase: UpdateProfileImageUseCase;
	SearchGeocodingUseCase: SearchGeocodingUseCase;
};

export type OutboundPortBeans = {
	ArticleCommandPort: ArticleCommandPort;
	ArticleDetailQueryPort: ArticleDetailQueryPort;
	AuthCommandPort: AuthCommandPort;
	AuthQueryPort: AuthQueryPort;
	CommentCommandPort: CommentCommandPort;
	CommentQueryPort: CommentQueryPort;
	FeedQueryPort: FeedQueryPort;
	GeocodingSearchPort: GeocodingSearchPort;
	GoogleOAuthPort: GoogleOAuthPort;
	HikingCommandPort: HikingCommandPort;
	LikeCommandPort: LikeCommandPort;
	MediaStoragePort: MediaStoragePort;
	MemberCommandPort: MemberCommandPort;
	MemberQueryPort: MemberQueryPort;
	NotificationCommandPort: NotificationCommandPort;
	NotificationQueryPort: NotificationQueryPort;
	ProfileCommandPort: ProfileCommandPort;
	ProfileImageStoragePort: ProfileImageStoragePort;
	ProfileQueryPort: ProfileQueryPort;
	TokenCodecPort: TokenCodecPort;
	TransactionPort: TransactionPort;
	ClockPort: ClockPort;
};

export type ConfigurationBeans = {
	CookieConfig: CookieConfig;
	TextEncoder: TextEncoder;
	DATABASE_PRIMARY_URL: string;
	DATABASE_REPLICA_URL: string;
	JWT_SECRET: string;
	GOOGLE_LOGIN_CLIENT_ID: string;
	GOOGLE_LOGIN_CLIENT_SECRET: string;
	NODE_ENV: typeof process.env.NODE_ENV;
	PUBLIC_MEDIA_BASE_URL: string;
};

export type AutowiredBeans = UseCaseBeans &
	OutboundPortBeans &
	ConfigurationBeans & {
		DrizzleTransactionRunner: unknown;
	};
